### ISSUE TITLE
背景色を白系統にする

### ISSUE THREAD

**Issue by fukuno-iniad** [fukuno-iniad/iniad-fake-homepage#1]
背景色の調整をお願いできますでしょうか。
基本の背景色は　#fbfbfb
スケジュールの背景色は　#f4f6f8
でどうでしょうか？

明光電子さんのホームページから取ってきました

**Comment by daigo-ishizuka** [comment]
背景色の調整を行いました！！
確認をお願いいたします

**Comment by fukuno-iniad** [comment]
ありがとうございます。確認することができました。
