### ISSUE TITLE
文字色の調整

### ISSUE THREAD

**Issue by fukuno-iniad** [fukuno-iniad/iniad-fake-homepage#2]
全体的な文字色の調整をお願いできますでしょうか。
基本の文字色は#5a5a5aでどうでしょうか。 UCTさんホームページから取ってきました。
また、INIADの差し色として#3c8dbc、#20ade5あたりを使っているのでご参考になれば幸いです。

**Comment by tsunekawakaori** [comment]
確認が遅くなってしまい申し訳ありません。
フォントカラーをご提案いただきありがとうございました！今ほどCSSを更新しましたので、ご確認いただければと思います。

スケジュール時間のフォントカラー（赤）はINIADサイトを参考にさせていただきました。
あわせて、＜h2＞のボーダーカラーも薄いグレーに変更してあります。

この他にも変更した方が良さそうな箇所が出てきましたらお知らせください。
引き続きよろしくお願いいたします。

**Comment by fukuno-iniad** [comment]
さっそくありがとうございます。　更新確認することができました。
