### ISSUE TITLE
フォントの調整

### ISSUE THREAD

**Issue by fukuno-iniad** [fukuno-iniad/iniad-fake-homepage#3]
h1、h2、h3、timeのフォントの大きさ調整をお願いできますでしょうか。
timeのfont-size 30pxが大き過ぎる気がするので、小さくしたうえで全体のバランス調整をしてもらえますと幸いです。

**Comment by shitayatatunori** [comment]
変える箇所は分かり３０から２０に変更したのですが、更新できているのかがわかりません
ご教授お願いできますでしょうか

**Comment by fukuno-iniad** [comment]
コメントありがとうございます。まだ更新できていないようなので、MOOCsの「git-02: Gitpod の活用とアジャイルソフトウェア開発」の「1. Gitpodを利用する」の10ページ目あたりから「コミット」と「プッシュ」の方法を確認してみてください。
分からないことがありましたら、また教えていただけましたら幸いです。

**Comment by shitayatatunori** [comment]
ご教授いただきありがとうございます
恐らくできたかと思いますのでご確認おねがいいたします

**Comment by daigo-ishizuka** [comment]
下谷の作業を代行し、フォントサイズの変更を行いました。ご確認をお願いいたします

**Comment by fukuno-iniad** [comment]
ありがとうございます。確認することができました。
